theme = "horizon_transparent"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"Z" = {Q = ":q!", Z = ":x", X = ":bc"}

[editor]
gutters = ["diagnostics", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar" 
