theme = "horizon_transparent"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"Z" = {Q = ":q!", Z = ":x", X = ":bc"}
"v" = {v = ":w"}
"r" = {r = ":reload-all"}

# [editor]
# gutters = ["diagnostics", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar" 
